name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate gource
      uses: NBprojekt/gource-action@v1.0.3
    - name: 'Upload gource video'
      uses: actions/upload-artifact@v2
      with:
        name: Gource
        path: ./jbradach-advent-of-code-2021.mp4
